### ISSUE TITLE
Feature request for workflow.construct_parameters

### ISSUE THREAD

**Issue by Meresmata** [up42/up42-py#155]
High, the geometry parameter for workflow.construct_parameters allows of list of boundary coordinates.

a) the bounds attribute of a shapely  polygon is a tuple of floats

so it raises: 

**ValueError: The provided geometry muste be a FeatureCollection, Feature, Dict, geopandas Dataframe, shapely Polygon, shapely Point or a list of 4 bounds coordinates.**
So, I manually have to make a list from the Tuple.

**Comment by chrieke** [comment]
Thanks for the feedback @Meresmata! We will consider this and get back to you soon!

**Comment by chrieke** [comment]
Decided to stick with the list, the accepted types are already plenty and not super simple to differentiate what is for what. Should be straight forward to provide the coords as a list and the error is relatively clear. Thank you for the feedback!
