### ISSUE TITLE
403 Permission Error for Viewshed 

### ISSUE THREAD

**Issue by RheagalFire** [up42/up42-py#243]
I am getting 403 Client Error for running a test Job as suggested in the Documentation(https://sdk.up42.com/examples/data-block-examples/nextmapone-viewshed-data-example/) 
![image](https://user-images.githubusercontent.com/60213893/127191163-42478c9f-f30a-4480-a3fb-7de7efa3e7c3.png)

**Comment by chrieke** [comment]
Hi @RheagalFire thanks for opening the issue! The [Nextmap One block](https://up42.com/marketplace/blocks/data/nextmapone-1m) has restricted access, please contact support@up42.com to unlock it for your account.
The error messaging on the API side is not very clear on this, we will try to improve this. Thank you!
