### ISSUE TITLE
Authenticatation with Project ID/Project API key

### ISSUE THREAD

**Issue by hlvlad** [up42/up42-py#557]
Hello,

From the code, I see that `authenticate()` method does accept `project_id`, `project_api_key` credentials. But I cannot find any relevant documentation, neither can I find a setting in my Up42 account to create new project/generate API key for it. Is this method still supported?

**Comment by seedlit** [comment]
@hlvlad Thanks for raising the issue.

> But I cannot find any relevant documentation, neither can I find a setting in my Up42 account to create new project/generate API key for it.

We don't support project based authentication for new users anymore. We have officially deprecated it, hence we have removed related documentation as well. I would recommend to use [username based authentication.](https://sdk.up42.com/authentication/)

> Is this method still supported?

Only for our existing users. And pretty soon we will completely remove it.

Let us know if you have any further questions.
I will close the issue in the meantime :)
