### ISSUE TITLE
Latest released version still does not support Python 3.12

### ISSUE THREAD

**Issue by adam-sikora** [up42/up42-py#580]
I can see you added support for newest version of Python but no release was made yet. Is there anything blocking you from releasing or did you just not get around to it?

Sorry for being pushy but the `up42-py` is the last package in our stack that still does not support Python 3.12 and is therefore blocking us from upgrading

**Comment by seedlit** [comment]
Hi @adam-sikora 
Thanks for your patience. We will release the new version tomorrow (it also involves some refactoring).

Also, we appreciate your feedback. Keep it coming :)
